export interface RoutinePhrase {
  spanish: string
  english: string
}

export interface Routine {
  id: string
  category: string
  emoji: string
  name: string
  context: string
  phrases: RoutinePhrase[]
}

export interface Category {
  id: string
  label: string
  emoji: string
}

export const categories: Category[] = [
  { id: "baby", label: "With baby", emoji: "👶" },
  { id: "smalltalk", label: "Small talk", emoji: "👋" },
  { id: "cafe", label: "Café", emoji: "☕" },
  { id: "travel", label: "Getting around", emoji: "🚆" },
]

// Clear, neutral Latin American Spanish using tú — approachable for a B1 learner.
export const routines: Routine[] = [
  {
    id: "greetings",
    category: "smalltalk",
    emoji: "👋",
    name: "Greetings",
    context: "Meeting someone new at the park or a playdate",
    phrases: [
      { spanish: "¿Qué tal?", english: "How's it going?" },
      { spanish: "¿De dónde eres?", english: "Where are you from?" },
      { spanish: "¿A qué te dedicas?", english: "What do you do?" },
      { spanish: "Encantado de conocerte.", english: "Nice to meet you." },
      { spanish: "Hasta luego.", english: "See you later." },
      { spanish: "¿Cómo te llamas?", english: "What's your name?" },
      { spanish: "Yo soy Bart, ¿y tú?", english: "I'm Bart, and you?" },
      { spanish: "¿Vives por aquí?", english: "Do you live around here?" },
      { spanish: "Este es Teo, mi hijo.", english: "This is Teo, my son." },
      { spanish: "¡Cuánto tiempo! ¿Cómo estás?", english: "It's been ages! How are you?" },
      { spanish: "Saludos a tu familia.", english: "Say hi to your family." },
      { spanish: "Que tengas buen día.", english: "Have a good day." },
    ],
  },
  {
    id: "cafe-ordering",
    category: "cafe",
    emoji: "☕",
    name: "At the café",
    context: "Ordering coffee with baby in the stroller",
    phrases: [
      { spanish: "¿Me traes la carta, por favor?", english: "Could you bring me the menu, please?" },
      { spanish: "Para mí, un café con leche.", english: "A café con leche for me." },
      { spanish: "¿Qué me recomiendas?", english: "What do you recommend?" },
      { spanish: "¿La propina está incluida?", english: "Is the tip included?" },
      { spanish: "La cuenta, por favor.", english: "The bill, please." },
      { spanish: "Un cortado y una medialuna, por favor.", english: "A cortado and a croissant, please." },
      { spanish: "¿Tienen leche sin lactosa?", english: "Do you have lactose-free milk?" },
      { spanish: "Sin azúcar, por favor.", english: "No sugar, please." },
      { spanish: "¿Me traes un poco más de agua?", english: "Could you bring me a bit more water?" },
      { spanish: "Está buenísimo, gracias.", english: "It's really good, thanks." },
      { spanish: "¿Puedo pagar con tarjeta?", english: "Can I pay by card?" },
      { spanish: "¿Nos podemos sentar afuera?", english: "Can we sit outside?" },
    ],
  },
  {
    id: "travel-basics",
    category: "travel",
    emoji: "🚆",
    name: "Travel basics",
    context: "Getting around town with the family",
    phrases: [
      { spanish: "¿Dónde está la estación?", english: "Where's the station?" },
      { spanish: "Un boleto al centro, por favor.", english: "A ticket to the centre, please." },
      { spanish: "¿A qué hora sale el tren?", english: "What time does the train leave?" },
      { spanish: "¿Cuánto cuesta?", english: "How much is it?" },
      { spanish: "¿Está libre este asiento?", english: "Is this seat free?" },
      { spanish: "Dos boletos, por favor.", english: "Two tickets, please." },
      { spanish: "¿Este bus va al centro?", english: "Does this bus go to the centre?" },
      { spanish: "¿Dónde me bajo para el museo?", english: "Where do I get off for the museum?" },
      { spanish: "¿Cada cuánto pasa el tren?", english: "How often does the train come?" },
      { spanish: "Perdón, ¿me dejas pasar?", english: "Excuse me, could you let me through?" },
      { spanish: "¿Hay ascensor? Vengo con cochecito.", english: "Is there a lift? I've got a stroller." },
      { spanish: "Nos bajamos en la próxima.", english: "We get off at the next stop." },
    ],
  },
  {
    id: "diaper",
    category: "baby",
    emoji: "🧷",
    name: "Diaper change",
    context: "Use these while changing the diaper",
    phrases: [
      { spanish: "Vamos a cambiar el pañal.", english: "Let's change your diaper." },
      { spanish: "Aquí vamos, ya casi.", english: "Here we go, almost done." },
      { spanish: "Levanta las piernas.", english: "Lift your legs." },
      { spanish: "¡Muy bien! Qué limpio estás.", english: "Well done! You're so clean." },
      { spanish: "¿Listo? ¡Listo!", english: "Ready? Done!" },
      { spanish: "Uy, alguien necesita un cambio.", english: "Uh oh, someone needs a change." },
      { spanish: "Acuéstate aquí, mi amor.", english: "Lie down here, my love." },
      { spanish: "Espera, no te muevas.", english: "Wait, don't wriggle." },
      { spanish: "¿Dónde están las toallitas?", english: "Where are the wipes?" },
      { spanish: "Un pañal limpio y listo.", english: "A clean diaper and we're done." },
      { spanish: "Ahora el botón y ya está.", english: "Now the snap and that's it." },
      { spanish: "Qué bien hueles ahora.", english: "You smell so nice now." },
    ],
  },
  {
    id: "feeding",
    category: "baby",
    emoji: "🍼",
    name: "Feeding",
    context: "During bottle or mealtime",
    phrases: [
      { spanish: "¿Tienes hambre?", english: "Are you hungry?" },
      { spanish: "Aquí viene la leche.", english: "Here comes the milk." },
      { spanish: "Rico, ¿verdad?", english: "Yummy, right?" },
      { spanish: "Más despacio, tranquilo.", english: "Slow down, easy." },
      { spanish: "¿Ya terminaste?", english: "Are you done?" },
      { spanish: "Abre la boca, aquí viene el avión.", english: "Open your mouth, here comes the aeroplane." },
      { spanish: "Una cucharadita más.", english: "One more little spoonful." },
      { spanish: "¿Quieres más?", english: "Do you want more?" },
      { spanish: "Mastica bien.", english: "Chew it well." },
      { spanish: "Se acabó, no hay más.", english: "All gone, there's no more." },
      { spanish: "Vamos a limpiar esa carita.", english: "Let's clean that little face." },
      { spanish: "¡Todo el plato! Muy bien.", english: "The whole plate! Well done." },
    ],
  },
  {
    id: "bath",
    category: "baby",
    emoji: "🛁",
    name: "Bath time",
    context: "While giving your little one a bath",
    phrases: [
      { spanish: "Hora del baño.", english: "Bath time." },
      { spanish: "El agua está calentita.", english: "The water is warm." },
      { spanish: "Vamos a lavar la cabecita.", english: "Let's wash your little head." },
      { spanish: "¡Qué rico el baño!", english: "What a nice bath!" },
      { spanish: "Ya terminamos. ¡Qué limpio!", english: "All done. So clean!" },
      { spanish: "¿Vamos a la bañera?", english: "Shall we go to the bath?" },
      { spanish: "Primero el pelito, después la pancita.", english: "First your hair, then your tummy." },
      { spanish: "Cuidado con los ojitos.", english: "Careful with your little eyes." },
      { spanish: "Mira cuántas burbujas.", english: "Look at all the bubbles." },
      { spanish: "¡Splash! ¡Qué divertido!", english: "Splash! How fun!" },
      { spanish: "Ahora la toalla, calentito.", english: "Now the towel, nice and warm." },
      { spanish: "A ponerse el pijama.", english: "Time to put on your pyjamas." },
    ],
  },
  {
    id: "bedtime",
    category: "baby",
    emoji: "🌙",
    name: "Bedtime",
    context: "Winding down for the night",
    phrases: [
      { spanish: "Es hora de dormir.", english: "It's time to sleep." },
      { spanish: "Buenas noches, mi amor.", english: "Good night, my love." },
      { spanish: "Cierra los ojitos.", english: "Close your little eyes." },
      { spanish: "Dulces sueños.", english: "Sweet dreams." },
      { spanish: "Te quiero muchísimo.", english: "I love you so much." },
      { spanish: "¿Te leo un cuento?", english: "Shall I read you a story?" },
      { spanish: "Uno más y a dormir.", english: "One more and then sleep." },
      { spanish: "Apagamos la luz.", english: "Let's turn off the light." },
      { spanish: "Aquí estoy, tranquilo.", english: "I'm right here, it's OK." },
      { spanish: "Duerme, mi cielo.", english: "Sleep, my darling." },
      { spanish: "Hasta mañana, mi vida.", english: "See you in the morning, sweetheart." },
      { spanish: "Que descanses.", english: "Rest well." },
    ],
  },
  {
    id: "wakeup",
    category: "baby",
    emoji: "☀️",
    name: "Waking up",
    context: "First thing in the morning",
    phrases: [
      { spanish: "¡Buenos días!", english: "Good morning!" },
      { spanish: "¿Dormiste bien?", english: "Did you sleep well?" },
      { spanish: "¡Ya despertaste!", english: "You woke up!" },
      { spanish: "Qué rico dormir, ¿verdad?", english: "Feels good to sleep, doesn't it?" },
      { spanish: "Hora de levantarse.", english: "Time to get up." },
      { spanish: "¿Cómo amaneció mi amor?", english: "How did my love wake up today?" },
      { spanish: "Ven aquí, un abrazo.", english: "Come here, give me a hug." },
      { spanish: "Vamos a abrir las cortinas.", english: "Let's open the curtains." },
      { spanish: "Mira, ya salió el sol.", english: "Look, the sun is up." },
      { spanish: "¿Qué vamos a hacer hoy?", english: "What are we going to do today?" },
      { spanish: "Primero la leche, después a jugar.", english: "First your milk, then playtime." },
      { spanish: "Qué sonrisa tan linda.", english: "What a lovely smile." },
    ],
  },
  {
    id: "outside",
    category: "baby",
    emoji: "🌿",
    name: "Going outside",
    context: "Heading out for a walk or to the park",
    phrases: [
      { spanish: "¡Vamos a salir!", english: "Let's go outside!" },
      { spanish: "Qué lindo día.", english: "What a beautiful day." },
      { spanish: "Mira el cielo.", english: "Look at the sky." },
      { spanish: "Siente el sol.", english: "Feel the sun." },
      { spanish: "¿Escuchas los pájaros?", english: "Do you hear the birds?" },
      { spanish: "Vamos a ponernos los zapatos.", english: "Let's put your shoes on." },
      { spanish: "¿Dónde está tu gorro?", english: "Where's your hat?" },
      { spanish: "Al cochecito, vamos.", english: "Into the stroller, let's go." },
      { spanish: "Mira, un perrito.", english: "Look, a little dog." },
      { spanish: "¿Ves ese árbol tan grande?", english: "Do you see that big tree?" },
      { spanish: "Di adiós con la manita.", english: "Wave bye-bye with your little hand." },
      { spanish: "Ya volvemos a casa.", english: "We're heading home now." },
    ],
  },
  {
    id: "playground",
    category: "smalltalk",
    emoji: "🛝",
    name: "At the playground",
    context: "Chatting with other parents while the kids play",
    phrases: [
      { spanish: "¿Cuántos años tiene el tuyo?", english: "How old is yours?" },
      { spanish: "El mío tiene casi dos.", english: "Mine is almost two." },
      { spanish: "¿Vienen mucho por aquí?", english: "Do you come here a lot?" },
      { spanish: "Se llevan bien, ¿no?", english: "They get along well, don't they?" },
      { spanish: "Nos vemos la próxima.", english: "See you next time." },
      { spanish: "¿Cómo se llama tu hija?", english: "What's your daughter's name?" },
      { spanish: "¡Qué grande está!", english: "She's gotten so big!" },
      { spanish: "¿Ya camina?", english: "Is he walking yet?" },
      { spanish: "Cuidado en el tobogán.", english: "Careful on the slide." },
      { spanish: "¿Te empujo más alto?", english: "Want me to push you higher?" },
      { spanish: "Nos toca irnos. Despídete.", english: "Time for us to go. Say bye." },
      { spanish: "Toma, se te cayó esto.", english: "Here, you dropped this." },
    ],
  },
  {
    id: "weather",
    category: "smalltalk",
    emoji: "🌤️",
    name: "Weather & the day",
    context: "Easy small talk about the weather",
    phrases: [
      { spanish: "Qué buen día hace hoy.", english: "What a nice day it is today." },
      { spanish: "Parece que va a llover.", english: "It looks like it's going to rain." },
      { spanish: "Hace bastante calor, ¿no?", english: "It's pretty hot, isn't it?" },
      { spanish: "Mejor llevamos abrigo.", english: "We'd better bring a coat." },
      { spanish: "A ver si sale el sol.", english: "Let's hope the sun comes out." },
      { spanish: "Qué frío hace esta mañana.", english: "It's so cold this morning." },
      { spanish: "Dicen que mañana llueve.", english: "They say it'll rain tomorrow." },
      { spanish: "Por fin salió el sol.", english: "The sun finally came out." },
      { spanish: "Está fresco para esta época.", english: "It's cool for this time of year." },
      { spanish: "Con este viento mejor no salimos.", english: "With this wind we'd better stay in." },
      { spanish: "Aprovechemos antes de que llueva.", english: "Let's make the most of it before it rains." },
      { spanish: "Qué calor, ¿no?", english: "So hot, isn't it?" },
    ],
  },
  {
    id: "bakery",
    category: "cafe",
    emoji: "🥐",
    name: "At the bakery",
    context: "Grabbing something at the bakery",
    phrases: [
      { spanish: "¿Qué tienes recién hecho?", english: "What's freshly made?" },
      { spanish: "Me llevo dos, por favor.", english: "I'll take two, please." },
      { spanish: "¿Tienes algo sin azúcar?", english: "Do you have anything without sugar?" },
      { spanish: "¿Me lo pones para llevar?", english: "Could you make it to go?" },
      { spanish: "¿Cuánto es todo?", english: "How much is it all?" },
      { spanish: "¿A qué hora abren mañana?", english: "What time do you open tomorrow?" },
      { spanish: "Media docena de estos, por favor.", english: "Half a dozen of these, please." },
      { spanish: "¿Este pan es de hoy?", english: "Is this bread from today?" },
      { spanish: "¿Qué me recomiendas para el desayuno?", english: "What do you recommend for breakfast?" },
      { spanish: "Uno de esos, por favor.", english: "One of those, please." },
      { spanish: "¿Tienes pan integral?", english: "Do you have wholemeal bread?" },
      { spanish: "Huele riquísimo aquí.", english: "It smells amazing in here." },
    ],
  },
  {
    id: "cafe-baby",
    category: "cafe",
    emoji: "🍼",
    name: "Café with a baby",
    context: "Sorting out space for the stroller",
    phrases: [
      { spanish: "¿Hay lugar para el cochecito?", english: "Is there room for the stroller?" },
      { spanish: "¿Tienes sillita para bebé?", english: "Do you have a high chair?" },
      { spanish: "¿Me calientas esto, por favor?", english: "Could you warm this up, please?" },
      { spanish: "¿Dónde puedo cambiarlo?", english: "Where can I change him?" },
      { spanish: "Un vaso de agua, por favor.", english: "A glass of water, please." },
      { spanish: "Venimos con bebé, ¿hay espacio?", english: "We're with a baby, is there space?" },
      { spanish: "¿Tienen algo suave para el bebé?", english: "Do you have anything soft for the baby?" },
      { spanish: "Perdón por el desorden.", english: "Sorry about the mess." },
      { spanish: "¿Me traes otra servilleta?", english: "Could you bring me another napkin?" },
      { spanish: "Se durmió. Hablemos bajito.", english: "He fell asleep. Let's keep it down." },
      { spanish: "¿El baño tiene cambiador?", english: "Does the bathroom have a changing table?" },
      { spanish: "Gracias por la paciencia.", english: "Thanks for your patience." },
    ],
  },
  {
    id: "taxi",
    category: "travel",
    emoji: "🚕",
    name: "Taxi & rideshare",
    context: "Getting a cab with the family",
    phrases: [
      { spanish: "¿Me llevas a esta dirección?", english: "Can you take me to this address?" },
      { spanish: "¿Tienes sillita para niños?", english: "Do you have a child seat?" },
      { spanish: "¿Cuánto cuesta hasta el centro?", english: "How much is it to the centre?" },
      { spanish: "Déjanos aquí, gracias.", english: "Drop us here, thanks." },
      { spanish: "¿Aceptas tarjeta?", english: "Do you take card?" },
      { spanish: "Buenas, a esta dirección, por favor.", english: "Hi, to this address, please." },
      { spanish: "Vamos con un bebé. Despacio, por favor.", english: "We've got a baby with us. Slowly, please." },
      { spanish: "¿Cuánto tarda hasta el aeropuerto?", english: "How long does it take to the airport?" },
      { spanish: "Para aquí, por favor.", english: "Stop here, please." },
      { spanish: "¿Me ayudas con el cochecito?", english: "Could you help me with the stroller?" },
      { spanish: "Quédate con el cambio.", english: "Keep the change." },
      { spanish: "¿Me das un recibo?", english: "Could I get a receipt?" },
    ],
  },
  {
    id: "directions",
    category: "travel",
    emoji: "🗺️",
    name: "Asking directions",
    context: "Finding your way around town",
    phrases: [
      { spanish: "¿Cómo llego al parque?", english: "How do I get to the park?" },
      { spanish: "¿Está lejos de aquí?", english: "Is it far from here?" },
      { spanish: "¿Puedo ir caminando?", english: "Can I walk there?" },
      { spanish: "¿Hay un baño cerca?", english: "Is there a bathroom nearby?" },
      { spanish: "Me perdí un poco.", english: "I'm a bit lost." },
      { spanish: "¿La farmacia queda por aquí?", english: "Is the pharmacy around here?" },
      { spanish: "¿A la derecha o a la izquierda?", english: "To the right or to the left?" },
      { spanish: "¿Sigo todo derecho?", english: "Do I keep going straight?" },
      { spanish: "¿Me lo muestras en el mapa?", english: "Could you show me on the map?" },
      { spanish: "¿Cuántas cuadras son?", english: "How many blocks is it?" },
      { spanish: "¿Se puede pasar con cochecito?", english: "Can you get through with a stroller?" },
      { spanish: "Gracias, muy amable.", english: "Thanks, that's very kind." },
    ],
  },
]
